### ISSUE TITLE
Recording using .avi discrepancies and file sizes

### ISSUE THREAD

**Issue by dmcconachie** [UM-ARM-Lab/arm_video_recorder#2]
Recording files to `.avi` generates huge files, and Adobe Premier does not accept the result as a valid file.

In addition we're getting strange results in terms of reported video duration. The actual recording duration was approximately 8 minutes, but the recorded video is reporting 16 minutes.

**Comment by bsaund** [comment]
I use (and recommend) the `.mp4`.

Describe the length problem.
What did you set as the `timeout_in_sec`?
How long between calling the service to `start` and `stop` the recording?
How long is the actual video?
Where does this "recorded video is reporting 16 minutes" come from?
Does the actual video play back with proper timing (1 second = 1 second)?

**Comment by dmcconachie** [comment]
This is the problem that VLC sees that is presumably the reason that Premier dislikes the file:

![image](https://user-images.githubusercontent.com/8689721/61148047-e6cbf580-a4ab-11e9-8ab7-b4005cb7133d.png)

Despite this message, I am able to move around the the video arbitrarily.

**Comment by dmcconachie** [comment]
`timeout_in_sec` was set to `3600.0`
Time between the service calls was roughly 8 minutes.

16 minute video comes from the following:
![image](https://user-images.githubusercontent.com/8689721/61148152-2397ec80-a4ac-11e9-893e-f513fa03e0d5.png)
![image](https://user-images.githubusercontent.com/8689721/61148179-31e60880-a4ac-11e9-8427-c6a3bb180a1b.png)

The video does not play back with the proper timing; it plays back at what appears to be half speed.
Actual video length as reported by VLC is 15:58

**Comment by dmcconachie** [comment]
These problems appear to be with `rosrun image_view video_recorder`, not this node.
