### ISSUE TITLE
OpenCV error with MP4 save format

### ISSUE THREAD

**Issue by LemonPi** [UM-ARM-Lab/arm_video_recorder#9]
`OpenCV: FFMPEG: tag 0x00000021/'!???' is not found (format 'mp4 / MP4 (MPEG-4 Part 14)')'` error when saving with mp4 extension, while fine with saving as `.avi`.

Service calls:
Fails
```
rosservice call /video_recorder ~/test.mp4 1 60
```
Succeeds
```
rosservice call /video_recorder ~/test.av1 1 60
```

**Comment by bsaund** [comment]
I'll take a look.
I believe the system has:

ubuntu version: 18.04 
ffmpeg version 3.4.8-0ubuntu0.2 Copyright (c) 2000-2020 the FFmpeg developers
ros and openrave

**Comment by bsaund** [comment]
Fixed by https://github.com/UM-ARM-Lab/arm_video_recorder/pull/10

The previously hardcoded fourcc code 0x00000021 seems to no longer work for mp4. This may be a python2 vs. python3 switch, an opencv switch, or something else.
Solution is to lookup the code using the opencv function
